# Generated by Django 4.2.15 on 2024-08-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_profile_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='profile_video',
        ),
    ]
